version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/rust/Dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./backend:/work/backend
    environment:
      - ALLOW_ORIGIN=${ALLOW_ORIGIN}

  web:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/home/node/app
